#!/usr/bin/env python3
"""Install the API-cost SessionEnd hook and Bash wrapper."""

from __future__ import annotations

import argparse
import json
import shlex
import shutil
import stat
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE_HOOK = PROJECT_ROOT / "src" / "codex_api_cost.py"
START_MARKER = "# >>> codex-hooks api-cost >>>"
END_MARKER = "# <<< codex-hooks api-cost <<<"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--codex-home",
        type=Path,
        default=Path.home() / ".codex",
        help="Codex configuration directory (default: ~/.codex)",
    )
    parser.add_argument(
        "--bashrc",
        type=Path,
        default=Path.home() / ".bashrc",
        help="Bash startup file to update (default: ~/.bashrc)",
    )
    parser.add_argument(
        "--config-dir",
        type=Path,
        default=Path.home() / ".config" / "codex-hooks",
        help="directory for generated shell integration",
    )
    parser.add_argument(
        "--spool-dir",
        type=Path,
        default=Path.home() / ".cache" / "codex-hooks" / "api-cost",
        help="directory for deferred per-session output",
    )
    return parser.parse_args()


def load_hooks(path: Path) -> dict[str, object]:
    if not path.exists():
        return {
            "description": "User-level Codex lifecycle hooks.",
            "hooks": {},
        }
    with path.open("r", encoding="utf-8") as stream:
        data = json.load(stream)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def install_hook(codex_home: Path, spool_dir: Path) -> tuple[Path, Path]:
    install_dir = codex_home / "hooks" / "api-cost"
    installed_hook = install_dir / "codex_api_cost.py"
    hooks_path = codex_home / "hooks.json"
    install_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
    spool_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
    shutil.copy2(SOURCE_HOOK, installed_hook)
    installed_hook.chmod(installed_hook.stat().st_mode | stat.S_IXUSR)

    hooks_data = load_hooks(hooks_path)
    hooks_table = hooks_data.setdefault("hooks", {})
    if not isinstance(hooks_table, dict):
        raise ValueError(f"{hooks_path}: 'hooks' must be an object")
    session_end = hooks_table.setdefault("SessionEnd", [])
    if not isinstance(session_end, list):
        raise ValueError(f"{hooks_path}: hooks.SessionEnd must be an array")

    command = (
        f"python3 {shlex.quote(str(installed_hook))} "
        f"--spool-dir {shlex.quote(str(spool_dir))}"
    )
    legacy_hook = codex_home / "hooks" / "api_cost.py"
    retained_groups: list[object] = []
    for group in session_end:
        if not isinstance(group, dict):
            retained_groups.append(group)
            continue
        handlers = group.get("hooks")
        if not isinstance(handlers, list):
            retained_groups.append(group)
            continue
        is_this_hook = any(
            isinstance(handler, dict)
            and any(
                str(candidate) in str(handler.get("command", ""))
                for candidate in (installed_hook, legacy_hook)
            )
            for handler in handlers
        )
        if not is_this_hook:
            retained_groups.append(group)

    retained_groups.append(
        {
            "hooks": [
                {
                    "type": "command",
                    "command": command,
                    "timeout": 3,
                }
            ]
        }
    )
    hooks_table["SessionEnd"] = retained_groups

    codex_home.mkdir(mode=0o700, parents=True, exist_ok=True)
    if hooks_path.exists():
        shutil.copy2(hooks_path, hooks_path.with_suffix(".json.bak"))
    temporary_path = hooks_path.with_suffix(".json.tmp")
    temporary_path.write_text(json.dumps(hooks_data, indent=2) + "\n", encoding="utf-8")
    temporary_path.replace(hooks_path)
    return installed_hook, hooks_path


def shell_fragment(spool_dir: Path) -> str:
    spool = shlex.quote(str(spool_dir))
    return f'''# Generated by codex-hooks. Re-run scripts/install.sh to update.
codex() {{
  local codex_api_cost_dir codex_api_cost_marker codex_api_cost_result
  local codex_api_cost_candidate codex_exit_status

  codex_api_cost_dir={spool}
  command mkdir -p -- "$codex_api_cost_dir" || {{
    command codex "$@"
    return $?
  }}

  codex_api_cost_marker="$(mktemp "$codex_api_cost_dir/.start.XXXXXX")" || {{
    command codex "$@"
    return $?
  }}

  command codex "$@"
  codex_exit_status=$?

  codex_api_cost_result=""
  for codex_api_cost_candidate in "$codex_api_cost_dir"/session-*.txt; do
    [[ -e "$codex_api_cost_candidate" && "$codex_api_cost_candidate" -nt "$codex_api_cost_marker" ]] || continue
    if [[ -z "$codex_api_cost_result" || "$codex_api_cost_candidate" -nt "$codex_api_cost_result" ]]; then
      codex_api_cost_result="$codex_api_cost_candidate"
    fi
  done

  if [[ -n "$codex_api_cost_result" && -s "$codex_api_cost_result" ]]; then
    printf '\\n'
    command cat -- "$codex_api_cost_result"
    command rm -f -- "$codex_api_cost_result"
  fi

  command rm -f -- "$codex_api_cost_marker"
  return "$codex_exit_status"
}}
'''


def replace_managed_block(text: str, replacement: str) -> str:
    start = text.find(START_MARKER)
    end = text.find(END_MARKER)
    if start == -1 and end == -1:
        return text.rstrip() + "\n\n" + replacement
    if start == -1 or end == -1 or end < start:
        raise ValueError("found an incomplete codex-hooks block in the shell startup file")
    end += len(END_MARKER)
    return text[:start].rstrip() + "\n\n" + replacement + text[end:].lstrip("\n")


def install_shell_wrapper(
    bashrc: Path,
    spool_dir: Path,
    config_dir: Path,
) -> tuple[Path, Path]:
    fragment_path = config_dir / "api-cost.bash"
    config_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
    fragment_path.write_text(shell_fragment(spool_dir), encoding="utf-8")

    source_line = f"[ -f {shlex.quote(str(fragment_path))} ] && . {shlex.quote(str(fragment_path))}"
    managed_block = f"{START_MARKER}\n{source_line}\n{END_MARKER}\n"
    existing = bashrc.read_text(encoding="utf-8") if bashrc.exists() else ""
    bashrc.write_text(replace_managed_block(existing, managed_block), encoding="utf-8")
    return fragment_path, bashrc


def main() -> int:
    args = parse_args()
    codex_home = args.codex_home.expanduser().resolve()
    bashrc = args.bashrc.expanduser().resolve()
    config_dir = args.config_dir.expanduser().resolve()
    spool_dir = args.spool_dir.expanduser().resolve()
    installed_hook, hooks_path = install_hook(codex_home, spool_dir)
    fragment_path, bashrc_path = install_shell_wrapper(bashrc, spool_dir, config_dir)

    print(f"Installed hook: {installed_hook}")
    print(f"Updated hooks: {hooks_path}")
    print(f"Installed shell wrapper: {fragment_path}")
    print(f"Updated shell startup: {bashrc_path}")
    print(f"Deferred output directory: {spool_dir}")
    print()
    print(f"Next: source {shlex.quote(str(bashrc_path))}")
    print("Then start Codex and use /hooks to trust the hook if prompted.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
